version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: symfony-app
        container_name: symfony-app
        volumes:
            - .:/srv/app
        working_dir: /srv/app
        ports:
            - "8000:8000"
        networks:
            - my_network

    db:
        image: mysql:8  # Используем MySQL 8
        container_name: symfony-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - my_network

volumes:
    db_data:

networks:
  my_network:
